apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  namespace: {{ .Values.namespace }}
  version: v1.27.3
  values:
    pilot:
      env:
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
        PILOT_ENABLE_GATEWAY_API_STATUS: "true"
        ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
