{{- if .Values.fixWebhookLoop.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-webhook-loop
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: fix-webhook-loop
    app.kubernetes.io/component: sail-operator
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fix-webhook-loop
    spec:
      restartPolicy: OnFailure
      serviceAccountName: servicemesh-operator3
      containers:
        - name: fix-webhook
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for webhooks to be created..."
              MUTATING_WEBHOOK="istio-sidecar-injector"
              VALIDATING_WEBHOOK="istio-validator-{{ .Values.namespace }}"
              MAX_WAIT=120

              # Wait for mutating webhook
              waited=0
              while ! kubectl get mutatingwebhookconfiguration ${MUTATING_WEBHOOK} 2>/dev/null; do
                if [ $waited -ge $MAX_WAIT ]; then
                  echo "WARNING: Timeout waiting for ${MUTATING_WEBHOOK}"
                  break
                fi
                echo "Waiting for ${MUTATING_WEBHOOK}..."
                sleep 5
                waited=$((waited + 5))
              done

              if kubectl get mutatingwebhookconfiguration ${MUTATING_WEBHOOK} 2>/dev/null; then
                echo "Annotating ${MUTATING_WEBHOOK}..."
                kubectl annotate mutatingwebhookconfiguration ${MUTATING_WEBHOOK} sailoperator.io/ignore=true --overwrite
              fi

              # Wait for validating webhook
              waited=0
              while ! kubectl get validatingwebhookconfiguration ${VALIDATING_WEBHOOK} 2>/dev/null; do
                if [ $waited -ge $MAX_WAIT ]; then
                  echo "WARNING: Timeout waiting for ${VALIDATING_WEBHOOK}"
                  break
                fi
                echo "Waiting for ${VALIDATING_WEBHOOK}..."
                sleep 5
                waited=$((waited + 5))
              done

              if kubectl get validatingwebhookconfiguration ${VALIDATING_WEBHOOK} 2>/dev/null; then
                echo "Annotating ${VALIDATING_WEBHOOK}..."
                kubectl annotate validatingwebhookconfiguration ${VALIDATING_WEBHOOK} sailoperator.io/ignore=true --overwrite
              fi

              echo "Done - webhook reconciliation loop fix applied"
{{- end }}
