#!/bin/bash
# Post-install message with next steps

echo ""
echo "============================================"
echo "  Sail Operator Installed Successfully!"
echo "============================================"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Patch istiod ServiceAccount (wait for operator to create it):"
echo ""
echo "   kubectl wait --for=create sa/istiod -n istio-system --timeout=300s"
echo "   kubectl patch sa istiod -n istio-system -p '{\"imagePullSecrets\": [{\"name\": \"redhat-pull-secret\"}]}'"
echo "   kubectl delete pod -n istio-system -l app=istiod"
echo ""
echo "2. Deploy your application (e.g., llm-d)"
echo ""
echo "3. After deploying llm-d, patch the gateway ServiceAccount:"
echo ""
echo "   export APP_NAMESPACE=llmd-pd"
echo "   kubectl get secret redhat-pull-secret -n istio-system -o yaml | sed \"s/namespace: istio-system/namespace: \${APP_NAMESPACE}/\" | kubectl apply -f -"
echo "   kubectl patch serviceaccount <gateway-sa-name> -n \${APP_NAMESPACE} -p '{\"imagePullSecrets\": [{\"name\": \"redhat-pull-secret\"}]}'"
echo "   kubectl delete pod -n \${APP_NAMESPACE} -l gateway.istio.io/managed=istio.io-gateway-controller"
echo ""
echo "See README.md for full documentation."
echo "============================================"
echo ""
